### ISSUE TITLE
Inconsistent spectrogram representation

### ISSUE THREAD

**Issue by vogelbam** [mbsantiago/whombat#10]
* Whombat version: 0.4.0
* Python version: 3.11
* Operating System: 20.04

### Description
Switching the selected best covering segment seems to impair the representation of calls. I'm not sure whether there's a satisfying solution to this issue, however, it might be confusing to labelers.

### What I Did
I opened a file for annotation and zoomed in. While scrolling horizontally I noticed a call changing its representation which made it look as if the box wasn't fit properly. It appears to be caused by selecting a different covering segment. Here's an example including the used and selected segments:

![Screenshot from 2024-03-26 10-45-07](https://github.com/mbsantiago/whombat/assets/52541998/ea389dc8-6bcd-4e1d-a5ab-a4236d509318)

Selected segment: 4
Start time: 1.2, End time: 1.7
Start time: 0.8999999999999999, End time: 1.4
Start time: 1.5, End time: 2

![Screenshot from 2024-03-26 10-44-06](https://github.com/mbsantiago/whombat/assets/52541998/a007536a-9e90-4dba-a127-c4d1ff101130)

Selected segment: 5
Start time: 1.5, End time: 2
Start time: 1.2, End time: 1.7
Start time: 1.7999999999999998, End time: 2.3

**Comment by mbsantiago** [comment]
Hi @vogelbam,

Thanks a lot for this issue!

I fully agree that this discrepancy can be confusing for the labeler. I think there are three potential sources for the problem:

1. There could be a bug causing a misalignment between the placement of spectrogram images and the drawing of annotations in the frontend canvas.
2. The STFT (Short-Time Fourier Transform) windows of the two audio segments don't align correctly. We may need to improve the selection of start and end times for the segments.
3. When applying a denoising algorithm or normalizing amplitude values, the output can vary depending on the whole audio content of the segment. As a result, even overlapping audio segments may exhibit significantly different appearances.

Unfortunately, this issue is an unintended consequence of computing the spectrogram in chunks. However, chunk processing is necessary to prevent Whombat from crashing with large recordings or becoming too slow to navigate.

I'll dive deeper into this issue to explore potential solutions, but I'm open to any ideas or suggestions you may have.

Thanks for the issue!

Best regards,
Santiago

**Comment by mbsantiago** [comment]
Hi @vogelbam 

I've changed substantially the way the spectrogram is rendered and this issue is now hopefully resolved. Let me know if you encounter it again.

Thanks again for the issue!
